Messages:
  Payday:
    - " "
    - " &6&L= PAYDAY = "
    - " "
    - "&aОбщая информация: "
    - " &7&l| &fКупленных бизнесов: %count_biz% "
    - " &7&l| &fПроведено времени в игре: %time% "
    - " "
    - "&cSALARY: "
    - " &d&| &fИтоговая сумма к зачислению: &a%money%$ "
  playTime: "&6&l[BUSINESS] &fВы поиграли недостаточное кол-во времени, поэтому мы не зачисляем зарплату!"
  buyUpdate: "&6&l[BUSINESS] &fВы купили улучшение &d{update}&f для бизнеса &c#{id}&f!"
  buyBusiness: "&6&l[BUSINESS] &fВы приобрели бизнес &c#{id}&f за &a{cost}$&f!"
  noMoney: "&6&l[BUSINESS] &fУ вас недостаточно денег для операции! &7(Необходимо: &a&n{need_money}$&7)"
  paymentTaxMessage: "&6&l[BUSINESS] &fС вашего счета снято &a{money}$ &fв качестве налога за бизнесы"
  alreadyHaveBiz: "&6&L[BUSINESS] &fБизнес &c#{id}&f уже имеется у вас!"
  sellBiz: "&6&l[BUSINESS] Вы продали бизнес &c#{id}&f за &a{cost}$"
  notHavePerm: "&cУ вас нет права &f{permission}&c!"
  error: "&c&l[ERROR] Произошла ошибка! Описание: {description}"
#
Business:
  #=========
  # Разделы:
  # RegistrationId - все айди бизнесов
  # Id - айди бизнесов по отдельности + настройка
  #===========
  # Настройка:
  # 0: пример айди бизнеса (Не указывайте отрицательные числа!)
  #   Slot - слот, где будет расположен предмет (Бизнес) в GUI
  #   Name - имя предмета, которое будет отображаться в GUI (Имена бизнесов не должны повторяться!)
  #   Item - предмет, который будет отображаться в GUI (Можно писать в нижнем регистре, например dirt)
  #   Class - класс бизнеса (LOW/MEDIUM/HIGH) для каждого класса ограничение в 20 бизнесов, отдельное меню
  #   Lore - описание предмета (Бизнеса)
  #   Cost - стоимость бизнеса
  #   Salary - зарплата с бизнеса в N секунд (Период настраивается в разделе Settings)
  #   CostSale - стоимость при продаже бизнеса
  #===========
  RegistrationId: # Все айдишники, на которые зареганы бизнесы, если айди какого-то бизнеса не будет вписан - возникнут ошибки!
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
  Id:
    0:
      Slot: 1
      Name: "&6&l[456374567547]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale: 4500
    1:
      Slot: 2
      Name: "&6&l[32453245234534]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    2:
      Slot: 3
      Name: "&6&l[324534252345]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    3:
      Slot: 4
      Name: "&6&l[324523452345]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    4:
      Slot: 5
      Name: "&6&l[123412552]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    5:
      Slot: 6
      Name: "&6&l[625345621q41]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    6:
      Slot: 7
      Name: "&6&l[13457631]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    7:
      Slot: 8
      Name: "&6&l[3543132]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    8:
      Slot: 9
      Name: "&6&l[236647]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    9:
      Slot: 10
      Name: "&6&l[1234612341]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    10:
      Slot: 11
      Name: "&6&l[51342]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    11:
      Slot: 12
      Name: "&6&l[5613245]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    12:
      Slot: 13
      Name: "&6&l[15345]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    13:
      Slot: 14
      Name: "&6&l[12313]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    14:
      Slot: 15
      Name: "&6&l[111111111111]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    15:
      Slot: 16
      Name: "&6&l[111111111]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    16:
      Slot: 17
      Name: "&6&l[11111111]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    17:
      Slot: 18
      Name: "&6&l[11111]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    18:
      Slot: 19
      Name: "&6&l[111]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
Menu:
  #=========
  # Разделы:
  # Global - применяется ко всем GUI в плагине
  # Main - основное меню плагина
  # ChangeClassBiz - меню выбора класс бизнеса
  # ChooseUpdateForBiz - выбор улучшения, которое хотите купить
  # UpdateBiz - основное меню улучшения бизнесов
  #===========
  # Настройка:
  # Name - имя предмета, которое будет отображаться в GUI
  # Slot - слот, где предмет будет расположен в GUI
  # Lore - описание предмета
  # Item - предмет, который будет отображаться в GUI (Можно писать в нижнем регистре)
  #===========
  Global:
    Close:
      Name: "&c&lx ЗАКРЫТЬ x"
      Slot: 0
      Lore: []
  Main:
    DevelopBusiness:
      Name: "&dУправление бизнесами"
      Slot: 22
      Item: CARROT_STICK
      Lore:
        - " "
        - "&7&l| &fВ этом разделе вы сможете"
        - "&7&l| &9управлять&f бизнесами,"
        - "&7&l| &fкоторые вы приобрели.,"
        - " "
        - "&6Нажмите, чтобы открыть... "
    BuySlot:
      Name: "&aПокупка бизнеса"
      Slot: 11
      Item: CHEST
      Lore:
        - " "
        - "&7&l| &fЗдесь вы сможете купить"
        - "&7&l| &fлюбой бизнес, который вас интересует."
        - " "
        - "&6Нажмите, чтобы открыть... "
    UpdateSlot:
      Name: "&eПокупка улучшений"
      Slot: 15
      Item: DIAMOND
      Lore:
        - " "
        - "&7&l| &fВ данном разделе вы сможете"
        - "&7&l| &aкупить &fулучшения для вашего бизнеса."
        - " "
        - "&6Нажмите, чтобы открыть... "
  ChangeClassBiz:
    LowClass:
      Name: "&8Эконом-класс"
      Item: COAL_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&8&lЭКОНОМ&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "
    MediumClass:
      Name: "&cЭлитный класс"
      Item: IRON_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&c&lЭЛИТНЫЙ&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "
    HighClass:
      Name: "&4Бизнес-класс"
      Item: DIAMOND_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&4&lБИЗНЕС&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "