Business:
  #=========
  # Разделы:
  # RegistrationId - все айди бизнесов
  # GlobalSettings - глобальные настройки
  # Id - настройка бизнесов
  #===========
  # Настройка:
  # 0: пример айди бизнеса (Не указывайте отрицательные числа!)
  #   Slot - слот, где будет расположен предмет (Бизнес) в GUI (Cлоты не должны повторяться!)
  #   Name - имя предмета, которое будет отображаться в GUI
  #   Item - предмет, который будет отображаться в GUI (Можно писать в нижнем регистре, например dirt)
  #   Class - класс бизнеса (LOW/MEDIUM/HIGH) для каждого класса ограничение в 20 бизнесов, отдельное меню
  #   Lore - описание предмета (Бизнеса)
  #   Cost - стоимость бизнеса
  #   Salary - зарплата с бизнеса в N секунд (Период настраивается в разделе Settings)
  #   CostSale - стоимость при продаже бизнеса
  #===========
  GlobalSettings:
    ColorGlassPane: 7 # 0(Белый),1(Оранжевый),2(Пурпурная),3(Голубая),4(Желтая),5(Лаймовая),6(Розовая),7(Серая),
                      # 8(Светло-серая),9(Бирюзовая),10(Фиолетовая),11(Синяя),12(Коричневая),13(Зеленая),14(Красная),15(Черная)
#
  RegistrationId: # Все айдишники, на которые зареганы бизнесы, если айди какого-то бизнеса не будет вписан - возникнут ошибки!
    - 0
    - 1
    - 2
    - 3
    - 4
  Id:
    0:
      Slot: 12
      Name: "&7[&aЦветочный магазин&7] "
      Item: APPLE
      Class: LOW
      Lore:
        - "&8Статус: {status} "
        - " "
        - "&6Описание: "
        - " &e>> &fВы получите небольшую лавочку, "
        - " &e>> &fкоторая торгует растения! "
        - " "
        - "&4Информация: "
        - " &e>> &fЦена: &611000$"
        - " &e>> &fПрибыль: &6110$/час"
        - " "
        - "&fНажмите &d[ЛКМ]&f, чтобы купить бизнес "
      Cost: 11000
      Salary: 110
    1:
      Slot: 13
      Name: "&7[&aЦветочный магазин&7] "
      Item: APPLE
      Class: LOW
      Lore:
        - "&8Статус: {status} "
        - " "
        - "&6Описание: "
        - " &e>> &fВы получите небольшую лавочку, "
        - " &e>> &fкоторая торгует растения! "
        - " "
        - "&4Информация: "
        - " &e>> &fЦена: &611000$"
        - " &e>> &fПрибыль: &6110$/час"
        - " "
        - "&fНажмите &d[ЛКМ]&f, чтобы купить бизнес "
      Cost: 11000
      Salary: 110
    2:
      Slot: 14
      Name: "&7[&aЦветочный магазин&7] "
      Item: APPLE
      Class: LOW
      Lore:
        - "&8Статус: {status} "
        - " "
        - "&6Описание: "
        - " &e>> &fВы получите небольшую лавочку, "
        - " &e>> &fкоторая торгует растения! "
        - " "
        - "&4Информация: "
        - " &e>> &fЦена: &611000$"
        - " &e>> &fПрибыль: &6110$/час"
        - " "
        - "&fНажмите &d[ЛКМ]&f, чтобы купить бизнес "
      Cost: 11000
      Salary: 110
    3:
      Slot: 15
      Name: "&7[&aЦветочный магазин&7] "
      Item: APPLE
      Class: LOW
      Lore:
        - "&8Статус: {status} "
        - " "
        - "&6Описание: "
        - " &e>> &fВы получите небольшую лавочку, "
        - " &e>> &fкоторая торгует растения! "
        - " "
        - "&4Информация: "
        - " &e>> &fЦена: &611000$"
        - " &e>> &fПрибыль: &6110$/час"
        - " "
        - "&fНажмите &d[ЛКМ]&f, чтобы купить бизнес "
      Cost: 11000
      Salary: 110
    4:
      Slot: 16
      Name: "&7[&aЦветочный магазин&7] "
      Item: APPLE
      Class: LOW
      Lore:
        - "&8Статус: {status} "
        - " "
        - "&6Описание: "
        - " &e>> &fВы получите небольшую лавочку, "
        - " &e>> &fкоторая торгует растения! "
        - " "
        - "&4Информация: "
        - " &e>> &fЦена: &611000$"
        - " &e>> &fПрибыль: &6110$/час"
        - " "
        - "&fНажмите &d[ЛКМ]&f, чтобы купить бизнес "
      Cost: 11000
      Salary: 110