Message:
  Update:
    BuyUpdate: "&6&l[BUSINESS] &fВы успешно &aприобрели&f улучшение &e&n%update_type%&f!"
  Money:
    SalaryReceived: "&6&l[BUSINESS] &fВы успешно сняли деньги с вашего бизнеса &c%salary%$"
    PaymentTax: "&6&l[BUSINESS] &fС вашего счета сняли налог &c%payment_tax%$ &fза ваш бизнес(-ы)!"
  Business:
    SellBusiness: "&6&l[BUSINESS] &fВы успешно &cпродали&f бизнес &d#%business_id%"
    BuyBusiness: "&6&l[BUSINESS] &fВы &aприобрели&f бизнес &d#business_id"
    AlreadyHaveBusiness: "&6&l[BUSINESS] &fВы уже имеете данный бизнес!"
  NotHavePerm: "&cУ вас нет права &f%permission%&c!"
#
Business:
  #=========
  # Разделы:
  # RegistrationId - все айди бизнесов
  # Id - айди бизнесов по отдельности + настройка
  #===========
  # Настройка:
  # 0: пример айди бизнеса (Не указывайте отрицательные числа!)
  #   Slot - слот, где будет расположен предмет (Бизнес) в GUI
  #   Name - имя предмета, которое будет отображаться в GUI (Имена бизнесов не должны повторяться!)
  #   Item - предмет, который будет отображаться в GUI (Можно писать в нижнем регистре, например dirt)
  #   Class - класс бизнеса (LOW/MEDIUM/HIGH) для каждого класса ограничение в 20 бизнесов, отдельное меню
  #   Lore - описание предмета (Бизнеса)
  #   Cost - стоимость бизнеса
  #   Salary - зарплата с бизнеса в N секунд (Период настраивается в разделе Settings)
  #   CostSale - стоимость при продаже бизнеса
  #===========
  RegistrationId: # Все айдишники, на которые зареганы бизнесы, если айди какого-то бизнеса не будет вписан - возникнут ошибки!
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  Id:
    0:
      Slot: 1
      Name: "&6&l[Пятерочка]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale: 4500
    1:
      Slot: 2
      Name: "&6&l[Такси]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    2:
      Slot: 3
      Name: "&6&l[Автомастерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    3:
      Slot: 4
      Name: "&6&l[Ресторан]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    4:
      Slot: 5
      Name: "&6&l[Аренда велосипедов]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    5:
      Slot: 6
      Name: "&6&l[Магазин обуви]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    6:
      Slot: 7
      Name: "&6&l[Магазин электроники]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    7:
      Slot: 8
      Name: "&6&l[Завод]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    8:
      Slot: 9
      Name: "&6&l[Аттракционы]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    9:
      Slot: 10
      Name: "&6&l[Парк]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    10:
      Slot: 11
      Name: "&6&l[Кинотеатр]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    11:
      Slot: 12
      Name: "&6&l[Магнит]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    12:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    13:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    14:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    15:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    16:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    17:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    18:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    19:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    20:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
    21:
      Slot: 13
      Name: "&6&l[Парикхмахерская]"
      Item: APPLE
      Class: LOW
      Lore:
        - ""
        - ""
        - ""
      Cost: 11000
      Salary: 110
      CostSale : 4500
Menu:
  #=========
  # Разделы:
  # Global - применяется ко всем GUI в плагине
  # Main - основное меню плагина
  # ChangeClassBiz - меню выбора класс бизнеса
  # ChooseUpdateForBiz - выбор улучшения, которое хотите купить
  # UpdateBiz - основное меню улучшения бизнесов
  #===========
  # Настройка:
  # Name - имя предмета, которое будет отображаться в GUI
  # Slot - слот, где предмет будет расположен в GUI
  # Lore - описание предмета
  # Item - предмет, который будет отображаться в GUI (Можно писать в нижнем регистре)
  #===========
  Global:
    Close:
      Name: "&c&lx ЗАКРЫТЬ x"
      Slot: 0
      Lore: []
  Main:
    DevelopBusiness:
      Name: "&dУправление бизнесами"
      Slot: 22
      Item: CARROT_STICK
      Lore:
        - " "
        - "&7&l| &fВ этом разделе вы сможете"
        - "&7&l| &9управлять&f бизнесами,"
        - "&7&l| &fкоторые вы приобрели.,"
        - " "
        - "&6Нажмите, чтобы открыть... "
    BuySlot:
      Name: "&aПокупка бизнеса"
      Slot: 11
      Item: CHEST
      Lore:
        - " "
        - "&7&l| &fЗдесь вы сможете купить"
        - "&7&l| &fлюбой бизнес, который вас интересует."
        - " "
        - "&6Нажмите, чтобы открыть... "
    UpdateSlot:
      Name: "&eПокупка улучшений"
      Slot: 15
      Item: DIAMOND
      Lore:
        - " "
        - "&7&l| &fВ данном разделе вы сможете"
        - "&7&l| &aкупить &fулучшения для вашего бизнеса."
        - " "
        - "&6Нажмите, чтобы открыть... "
  ChangeClassBiz:
    LowClass:
      Name: "&8Эконом-класс"
      Item: COAL_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&8&lЭКОНОМ&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "
    MediumClass:
      Name: "&cЭлитный класс"
      Item: IRON_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&c&lЭЛИТНЫЙ&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "
    HighClass:
      Name: "&4Бизнес-класс"
      Item: DIAMOND_ORE
      Lore:
        - " "
        - "&7&l| &fВ данном разделе содержаться "
        - "&7&l| &fвсе бизнесы уровня &7[&4&lБИЗНЕС&7]&f. "
        - " "
        - "&6Нажмите, чтобы открыть раздел... "